---
-
  name: "Campfire"
  desc: "Campfire adapter"
  vars:
    -
      name: "HUBOT_CAMPFIRE_TOKEN"
      desc: "Campfire API token"
    -
      name: "HUBOT_CAMPFIRE_ROOMS"
      desc: "Campfire room IDs, separated by a commas"
    -
      name: "HUBOT_CAMPFIRE_ACCOUNT"
      desc: "Campfire account subdomain"

-
  name: "Flowdock"
  desc: "Flowdock adapter"
  vars:
    -
      name: "HUBOT_FLOWDOCK_LOGIN_EMAIL"
      desc: "Flowdock login email"
    -
      name: "HUBOT_FLOWDOCK_LOGIN_PASSWORD"
      desc: "Flowdock login password"

-
  name: "GTalk"
  desc: "Google Talk adapter"
  vars:
    -
      name: "HUBOT_GTALK_USERNAME"
      desc: "Google Talk username"
    -
      name: "HUBOT_GTALK_PASSWORD"
      desc: "Google Talk password"
    -
      name: "HUBOT_GTALK_WHITELIST_DOMAINS"
      desc: "Hubot will accept contact requests from these domains"
    -
      name: "HUBOT_GTALK_WHITELIST_USERS"
      desc: "Hubot will accept contact requests from these users"

-
  name: "HipChat"
  desc: "HipChat adapter"
  vars:
    -
      name: "HUBOT_HIPCHAT_TOKEN"
      desc: "HipChat API token"
    -
      name: "HUBOT_HIPCHAT_JID"
      desc: "HipChat JID"
    -
      name: "HUBOT_HIPCHAT_NAME"
      desc: "HipChat name for your robot, leave blank to use the Robot name"
    -
      name: "HUBOT_HIPCHAT_PASSWORD"
      desc: "HipChat password"
    -
      name: "HUBOT_HIPCHAT_ROOMS"
      desc: "HipChat rooms to join, separated by commas, eave blank to join all"

-
  name: "IRC"
  desc: "IRC adapter"
  vars:
    -
      name: "HUBOT_IRC_NICK"
      desc: "IRC nick for your robot, leave blank to use the Robot name"
    -
      name: "HUBOT_IRC_SERVER"
      desc: "IRC server address"
    -
      name: "HUBOT_IRC_PORT"
      desc: "IRC server port, leave blank to use the default (6667)"
    -
      name: "HUBOT_IRC_ROOMS"
      desc: "IRC rooms, separated by commas"
    -
      name: "HUBOT_IRC_PASSWORD"
      desc: "IRC server password, leave blank if not required"
    -
      name: "HUBOT_IRC_NICKSERV_PASSWORD"
      desc: "IRC nickserv password, leave blank if not required"

-
  name: "Partychat-Hooks"
  desc: "Partychat-hooks Adapter"
  vars:
    -
      name: "HUBOT_POST_ENDPOINT"
      desc: "Partychat Hook Endpoint"

-
  name: "Talker"
  desc: "Talker adapter"
  vars:
    -
      name: "HUBOT_TALKER_TOKEN"
      desc: "Talker API token"
    -
      name: "HUBOT_TALKER_ROOMS"
      desc: "Talker rooms to join, separated to commas"

-
  name: "Twilio"
  desc: "Twilio adapter"
  vars:
    -
      name: "HUBOT_SMS_SID"
      desc: "Twilio SID"
    - 
      name: "HUBOT_SMS_TOKEN"
      desc: "Twilio API token"
    -
      name: "HUBOT_SMS_FROM"
      desc: "Twilio number to send the reply from"

